name: flutter_data_persistence_api_demo
description: A simple Flutter demo project for data persistence and API interaction.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.1.1
  path_provider: ^2.0.14
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
